parameters:
    prismic.api.endpoint:         "https://lesbonneschoses.prismic.io/api"
    prismic.api.accessToken:      null
    prismic.api.clientId:         null
    prismic.api.clientSecret:     null

services:
    prismic.helper:
        class:      Prismic\PrismicStarterProjectBundle\Helper\PrismicHelper
        arguments:  [ %prismic.api.endpoint%, %prismic.api.accessToken%, %prismic.api.clientId%, %prismic.api.clientSecret% ]

    prismic.linkResolver:
        class:      Prismic\PrismicStarterProjectBundle\Helper\LinkResolver
        arguments:  [ @router ]

    prismic.context:
        class:      Prismic\PrismicStarterProjectBundle\Helper\PrismicContext
        scope:      request
        arguments:  [ @request, @prismic.helper, @prismic.linkResolver ]
